//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Userr
    {
        public int userr_id { get; set; }
        public string userr_name { get; set; }
        public string user_password { get; set; }
        public int user_age { get; set; }
        public string user_gender { get; set; }
        public int user_number { get; set; }
        public string user_city { get; set; }
    }
}
